# Generated by Django 4.0.4 on 2022-07-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
