# Generated by Django 4.0.4 on 2022-07-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('House', 'House'), ('Fashion', 'Fashion'), ('Everything Else', 'Everything Else')], max_length=64),
        ),
    ]
