# Generated by Django 4.0.4 on 2022-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_initial_bid_listing_lister_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('C', 'Clothing'), ('E', 'Electronics'), ('EE', 'Everything Else')], default=None, max_length=2),
        ),
    ]
