# Generated by Django 4.0.4 on 2022-07-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
